nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.2.3.cjs



npmRegistries:
  "https://packages.aliyun.com/66e2dd9f79b7fe080f32665b/npm/npm-registry/":
    npmAuthToken: 3e6ad778-797d-43fb-a03a-bafb54d23665
    npmAlwaysAuth: true
npmRegistryServer: "https://packages.aliyun.com/66e2dd9f79b7fe080f32665b/npm/npm-registry/"
